### ISSUE TITLE
Deviations

### ISSUE THREAD

**Issue by paulduchesne** [FIAF/modelling-workshops#11]
Highlight instances where the ontology currently deviates intentionally from the cataloguing manual.

*2.3.4.2 Projection Characteristic*

- `projection characteristic` has been renamed as `image characteristic` to allow for instance where ratio information is related to an item which is not "projected" (eg video, DVD).

*2.3.5.3 Duration*

- `duration` has been incorporated as an `extent` with relevant types.

*3.1.3 Holding Institution*

- `institutions` do not exist as a separate class, but are just `agents`.

*3.1.5.16/17/20 Codec and Bit Depth*

- a digital file can contain streams which each have their own codec and bit depth information, so a new entity has been introduced (`stream`) which sits in between the digital item and the `codec` and `bit depth` info.

*3.1.5.22 Source Software*

- definition at `3.1.5.22` describes the "device used to play a digital file" (eg VLC). While this is certainly useful to know from a digital preservation perspective, surely it is more important (and the "source") to know the software used to create the digital file (eg FFmpeg).

*D.7.7 Item Base – Film or Video*

- removed `video` from `base` list to prevent colision with format:video, also because it seems inappropriate as base value.

*D.7.9 Item File Size – Digital*

- added Megabyte and Terabyte as relevant to current archival practise.

*D.7.10 Item Codec type*

- I presume that the "NIL" part of `NIL ProRes 422 (HQ)` is a typo.

*D.7.13 Item Sound System*

- `mute` is removed from `sound system` as it is already available at `sound characteristic` level, and this feels more appropriate.

*D.7.16 Item Stock*

- manufacturer is presented as carrier-type agnostic.

*D.8 Manifestation Agent Types*

- these are represented not as `agent` types (equivalent of person, organisation), but as `activity` types (equivalent to producer or cast member).

*D.10 Manifestation Publication Types*: 

- `publication` is removed from the type list, to prevent the tautology of a `preservation event` being a subclass of a `preservation event`.
- `broadcast` is listed twice, only represented in the ontology once.
- `unknown event` is represented, but I would argue that a `publication event` (parent class) with no subclass means exactly the same thing.

*other*

- `work` and `variant` have been combined into a single entity `work/variant`.
- `carrier` has been added as a sub-item tier.

**Comment by paulduchesne** [comment]
Note that this could also be a good space to talk about things which *should* be deviated from.

**Comment by paulduchesne** [comment]
I was going to kick this off with suggesting a change to the Colour Characteristics vocabulary (D.7.11). 

Currently it comprises:
```
Colour
Colour + Black & White
Tinted
Black and white
Black and white (tinted)
Black and white (toned)
Black and white (tinted and toned)
Sepia
```

My suggestion would be to reduce the 8 options to 6:

```
Colour
Black and White
Black and White/Colour
Tinted
Toned
Tinted/Toned
```

The changes I am proposing are removing the "black and white" from the `tinted` and `toned` terms, as these are self-evident on the understanding that we are talking about film which has been physically tinted or toned (a processing technique), not a creative colour grade (eg "The Matrix", "Out Of Sight"). It has also always struck me as off to use the language "Black and White" with "tinted and toned", as a tinted and toned print will contain neither black nor white! I was also not sure why Sepia would be considered a distinct tone. 

Another question is how to indicate a combination of techniques as opposed to interleaved techniques, for example the difference between a film which contains tinted-only sequences interspersed with toned-only sequences, against a film which is tinted-and-toned throughout.

I would suggest the former would be expressed as multiple distinct statements (eg `film work` > `has colour characteristic` > `tinted` AND `film work` > `has colour characteristic` > `toned`) as opposed to the print containing tinted/toned film throughout  (eg `film work` > `has colour characteristic` > `tinted/toned`).

This logic could also be applied to distinguish films which contain sequences of both black and white AND colour (within the same frame - eg "Pleasentville", "Schindler's List") as `black and white/colour` and those which contain discrete sequences of each (eg "Daises", "Kill Bill") as `black and white` AND `colour`.

**Comment by annahoegner** [comment]
D.7.7 Item Base – Film or Video
removed video from base list to prevent colision with format:video, also because it seems inappropriate as base value.

How about introducing magnetic tape as base? I guess that is what this refers to.

**Comment by annahoegner** [comment]
D.7.11

In the VHH project we go with an even more reduced vocabulary: bw, color, color & bw and moved tinting and toning to the color film process, wich they technically are. In a digitized film colors achieved through tinting or toning are no different from colors achieved through other processes.

**Comment by torbjornbp** [comment]
> I am no chemist, but I wonder if there is an equivalent base as with film - ie is the plastic base of magnetic tape just polyester?

I don't think that's a viable. It can be acetate and polyester. If we expand to include film sound production elements, we also have additional bases like PET and PVC.

**Comment by paulduchesne** [comment]
Would that base composition be tied to format, time period or manufacturer? I suppose it is also obvious that there are very real safety and storage concerns tied to film base, hence a level of detail not present in other formats.

A purist approach would probably be that you are not compromising the vocabulary to cater to different methods of assessment, ie if base composition is not known beyond "magnetic tape", then it should be left blank as the "magnetic tape"ness can be inferred by being videotape.

**Comment by natashafairbairn** [comment]
D.7.10 Item Codec type

I presume that the "NIL" part of NIL ProRes 422 (HQ) is a typo.

Yes, it is a mistake in the Manual - a missing return - ProRes422 (HQ) should be listed below NIL

**Comment by paulduchesne** [comment]
Can be opened under the ontology repo at https://github.com/FIAF/FIAFcore
