### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by paulduchesne** [FIAF/modelling-workshops#13]
Space to discuss licencing of ontology. While I favour CC0 generally for ideological reasons, a consideration is that this project does incorporate textual and conceptual elements from other FIAF resources, which may carry their own licences.

other examples:

- [PBCore uses CC-BY](https://pbcore.org/license) (although confusingly the [git instance seems to be CC0](https://github.com/PBCore-AV-Metadata/PBCore_2.1/blob/master/LICENSE)). 
- [BIBFRAME appears to be CC0](https://github.com/lcnetdev/bibframe-ontology/blob/main/dev/bibframe/ontology/rdf.xml).

**Comment by stephenmcconnachie** [comment]
This is a useful resource, possibly, to inform thinking: the Wikimedia COmmons 'Choosing a Licence' article - https://commons.wikimedia.org/wiki/Commons:Choosing_a_license

**Comment by paulduchesne** [comment]
Thanks @stephenmcconnachie. One of the issues identified in the last meeting is that the work here leans very heavily on the cataloguing manual, which does not currently carry a licence.

**Comment by stephenmcconnachie** [comment]
We should advocate a process of asserting CC-BY or CC-0 for the Manual in tandem with this conversation, I think.... Might take longer as there is a print version without it etc. But at least we could align the two licencing conversations.

**Comment by paulduchesne** [comment]
Great idea! I will bring this up with @heftberger.

**Comment by paulduchesne** [comment]
Thank you for this information @annahoegner, sorry I only saw it now. I am going to close this ticket at after some internal conversation there is support that the ontology is released under CC-BY.
