### ISSUE TITLE
Activity naming convention

### ISSUE THREAD

**Issue by paulduchesne** [FIAF/modelling-workshops#14]
Due to the activities being mostly pulled from the Filmographic Glossary, they have inherited multiple tenses (director, directing, directed by). This also plays into a discussion around how verb can be preferences for languages in which the noun features gender variants (French, German, traditional English equivalent "Actor/Actress"), where the verb is not modified. There are however, at least in English, many terms which are rarely heard used in verb form ("camera assistanting"? "wardrobing"?).

Related to this, a need to add a property to express the (monolingual?) agent activity credit, as expressed on the screen, which can be applied to the `activity` blank node.

**Comment by sidesg** [comment]
I was wondering if it would be useful to add more hierarchical structure to the Activity classes. I was looking how some Cinémathèque québécoise data would map to the ontology, and I found that the terminal classes were sometimes too precise for the classes our internal catalogue uses, and the next level up was often too general. Adding one more level of hierarchy to the Activity classes might make it easier to map a wider variety of source data to the ontology.

For example, the FIAF Glossary has a pretty fine-grained vocabulary related to costuming: Costume Maker, Costume Supervisor, Costume Supplier, Costumer, Costume Designer, Gowns, and Wardrobe Supervisor are all sibling subclasses of "Production Design Activity". In our catalogue data, the CQ subsumes all these under a single entry in our cast/crew controlled vocabulary, “Costumes”.

Mapping the CQ data, we could either pick a semi-arbitrary most-representative class to map our Costumes role to (for example, declaring the CQ’s “Costumes” to be equivalent to fiaf:CostumeDesigner). But this would end up creating triplets making assertions that aren’t necessarily true. 

This situation could be improved by adding a “Costume Activity” (or some name to this effect) subclass to Production Design Activity and making the fine-grained costume activities subclasses of “Costume Activity”. 

I used the costuming classes as an example, but there are other cases where natural groups of Activity classes could be grouped together to allow the ontology to accommodate source data with differing levels of specificity.

Hope this falls within the scope of the current state of the project.

**Comment by paulduchesne** [comment]
Thank you for these comments @sidesg and @annahoegner, and this is a good point that the hierachy could be even further nested - as you have noted, currently it is just reflecting that `CostumeDesigner` (for example) as a subclass of `ProductionDesignActivity` without a further grouping of Costume Activities. 

I feel this structure could also cause some problems (or at least, confusion) where the name of the family can also be applied to a child node, eg we currently have `Directing Activity` to encompass all related directing activities (assistant director, second-unit director, casting) and a `Direction` related to the specific role of "director".

**Comment by paulduchesne** [comment]
> Hope this falls within the scope of the current state of the project.

This is also a good point - I think a lot of considerations become apparent as soon as you try and match this model to actual film data, as you have done (I have also just published a list of Bundesarchiv-related questions under #8). 

My thinking generally was that the purpose of the v1 is really to put forward a coherent model which we feel accurately reflects existing FIAF resources. The subsequent mapping to significant datasets should uncover areas which require reconsideration, and so I see the v2 as being a major "stable" release.

**Comment by sidesg** [comment]
Sounds reasonable; I'll try to muddy the waters incrementally rather than all at once :)
