### ISSUE TITLE
Before I forget about it, another question which I wanted to bring up is whether we should be using the D.1 "work description type" in our modelling at this stage at all. Following @stephenmcconnachie's recommendation for ruthless pragmatism, I was thinking that, despite it being presented as a "complete" vocabulary in both the standard and manual, whether it is very useful for us in this context. From what I have seen of the archives who are using it, there seemed to be 98% Monographic Works, 2% Serial and Collection/Analytic were extremely rare (if at all). What was your breakdown in this regard @ladislav-nfa ?

### ISSUE THREAD

**Issue by natashafairbairn** [FIAF/modelling-workshops#2]
Before I forget about it, another question which I wanted to bring up is whether we should be using the D.1 "work description type" in our modelling at this stage at all. Following @stephenmcconnachie's recommendation for ruthless pragmatism, I was thinking that, despite it being presented as a "complete" vocabulary in both the standard and manual, whether it is very useful for us in this context. From what I have seen of the archives who are using it, there seemed to be 98% Monographic Works, 2% Serial and Collection/Analytic were extremely rare (if at all). What was your breakdown in this regard @ladislav-nfa ?

_Originally posted by @paulduchesne in https://github.com/FIAF/modelling-workshops/issues/1#issuecomment-1386659123_

**Comment by natashafairbairn** [comment]
Actually the Work Description Type is core to both structuring and categorisation so it is important to use it, even if in majority of cases it will be Monographic. We have over 8,000 Analytic work records and c.230 Collection Work records - and again this may be due to the nature of our collections and activities at the BFI, e.g. most of our Analytic records pertain to individual elements from newsreel Topical Budget. Individual records for these (linked as children of a Monographic Work for the whole newsreel episode) are needed because the BFI streams them as individual films on BFIplayer (i.e. each of 5 individual story elements in a newsreel issue are titled and streamed rather than the newsreel issue as a whole) and each has its own individual Internet Manifestation. Collections are used with home movie collections and production materials collections (which aren't Series/Serials in the same sense as intended film or TV serials). My only issue with Work Description type  is with its EN15907 definitions - which have been lifted straight from a bibliographic standard unchanged and are therefore difficult to get your head round to apply to a moving image context - and in the manual we tried to tighten up and clarify the definitions and fit these better into a moving image context.

**Comment by paulduchesne** [comment]
conversation continued in #1
